name: Mirror to GitLab Repo

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        with:
          source-repo: "git@github.com:kathryn-garside/example-mirror-repo.git"
          destination-repo: "git@gitlab.com:kathryn-garside/example-mirror-target.git"



# name: Mirroring

# on: [push, delete]

# jobs:
#   to_gitlab:
#     runs-on: ubuntu-latest
#     steps:                                              # <-- must use actions/checkout before mirroring!
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#       - uses: pixta-dev/repository-mirroring-action@v1
#         with:
#           target_repo_url:
#             git@gitlab.com:kathryn-garside/example-mirror-target.git
#           ssh_private_key:                              # <-- use 'secrets' to pass credential information.
#             ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
